// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateIDCards():Promise<string>;

export function SelectDataFile():Promise<void>;

export function SelectIDTemplateFile():Promise<void>;

export function SelectOutputDirectory():Promise<void>;
