// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateIDCards() {
  return window['go']['main']['App']['GenerateIDCards']();
}

export function SelectDataFile() {
  return window['go']['main']['App']['SelectDataFile']();
}

export function SelectIDTemplateFile() {
  return window['go']['main']['App']['SelectIDTemplateFile']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}
